### ISSUE TITLE
Maintenance: Set up monitoring for the site.

### ISSUE THREAD

**Issue by potthast** [ir-anthology/ir-anthology#16]
E.g., use the Webis Prometheus instance.

**Comment by matthias-hagen** [comment]
Can you please point us to the place where it is implemented in Prometheus?

**Comment by sebgntr** [comment]
Consul is monitoring for availability (only internally, see: https://consul.webis.de/ui/webis/services/iranthology/instances) and monitoring emails are sent if the website is unavailable.
