### ISSUE TITLE
Page: Line break between search input and submit button on mobile.

### ISSUE THREAD

**Issue by potthast** [ir-anthology/ir-anthology#17]
![image](https://user-images.githubusercontent.com/1148967/111052939-00cb9180-8460-11eb-8d72-5b16b18e728c.png)

**Comment by najtin** [comment]
i can't reproduce it. With which browser and os did you find this?

**Comment by potthast** [comment]
In the newest version it should already be solved. It occurs in the current version on Android Chrome on a Huawei.
