### ISSUE TITLE
Page: Right-side buttons on a paper's page have 2-3 lines, which is excessive.

### ISSUE THREAD

**Issue by potthast** [ir-anthology/ir-anthology#19]
![image](https://user-images.githubusercontent.com/1148967/111053011-90714000-8460-11eb-907c-582d91576e03.png)

**Comment by najtin** [comment]
info: happens with very specific screen sizes, between 1920p and mobile

**Comment by potthast** [comment]
Well, we can just use non-breaking spaces to make sure it never happens.

**Comment by najtin** [comment]
introducing non-breaking spaces causes the buttons to grows out of the view area. my suggestion would be to leave it as is, because it should not be a problem for almost any device at full window size.

**Comment by sebgntr** [comment]
Caused: https://github.com/ir-anthology/ir-anthology/issues/98
