### ISSUE TITLE
Page: Contents panels should only be shown if there is more than one entry

### ISSUE THREAD

**Issue by potthast** [ir-anthology/ir-anthology#20]
![image](https://user-images.githubusercontent.com/1148967/111053038-cf9f9100-8460-11eb-9f4c-b78bb4e39e4b.png)

**Comment by potthast** [comment]
Compare
https://ir.webis.de/anthology/volumes/1979.sigir_conf-default/
with
https://ir.webis.de/anthology/events/sigir_conf-1979/

The latter looks better, but the two paper count and full bib download buttons are missing.

**Comment by najtin** [comment]
i could not find a way to do it in hugo. for now this is solved by a hack in javascript.

**Comment by potthast** [comment]
Alright, leave a comment to this effect, also perhaps with reference to this issue in the code.
