### ISSUE TITLE
Data: CIKM 21 shows a single paper from CIKM-20

### ISSUE THREAD

**Issue by potthast** [ir-anthology/ir-anthology#3]
https://ir.webis.de/anthology/events/cikm_conf-2021/

**Comment by najtin** [comment]
this should be solved as soon as #14 is done

**Comment by najtin** [comment]
this is visually fixed, but the underlying problem persists so i would like to keep this issue open for now.

**Comment by potthast** [comment]
But the fix is not deployed, yet, right?

![image](https://user-images.githubusercontent.com/1148967/111694584-5920db80-8832-11eb-9a4a-a0a4dc5c759e.png)

Could you fast-track that?

**Comment by najtin** [comment]
this is resolved
