### ISSUE TITLE
Fix parsing of authors who have ORCIDs in the DBLP entry

### ISSUE THREAD

**Issue by nmeuschke** [ir-anthology/ir-anthology#45]
#### Issue description
The extraction of author names from DBLP seems to fail when an ORCID is assigned to an author as part of the DBLP entry.

**Example 1:** [IR-Anthology entry](https://ir.webis.de/anthology/2013.sigir_conf-default.111/) | [DBLP entry](https://dblp.org/rec/conf/sigir/GippMBLN13.html) — The IR-Anthology recognized 1 of 5 authors. The four missing authors have ORCIDs shown in the DBLP entry. 

**Example 2:** [IR-Anthology entry](https://ir.webis.de/anthology/2018.sigir_conf-default.59/) | [DBLP entry](https://dblp.org/rec/conf/sigir/MeuschkeSSG18.html) — The IR-Anthology recognized 2 of 3 authors. The missing author is the only one having an ORCID shown in the DBLP entry.

**Example 3:** [IR-Anthology entry](https://ir.webis.de/anthology/2016.sigir_conf-default.22/) | [DBLP entry](https://dblp.org/rec/conf/sigir/SchubotzGLCMGYM16.html) — The IR-Anthology recognized 5 of 8 authors. The three missing authors have ORCIDs shown in the DBLP entry.

**Example 4:** [IR-Anthology entry](https://ir.webis.de/anthology/2017.cikm_conf-default.312/) | [DBLP entry](https://dblp.org/rec/conf/cikm/MeuschkeSHSG17.html) — The IR Anthology recognized 2 of 5 authors. The three missing authors have ORCIDs shown in the DBLP entry.

The DBLP BibTeX files for all four examples are correct.

**Comment by najtin** [comment]
Thanks for reporting the issue. This is due to a faulty regex. I am taking care of fixing it and will report back as soon as the changes go live.

As a side note: We are currently reworking the data collection and data extraction processes, which should avoid such problems.

**Comment by nmeuschke** [comment]
Great! Thanks for taking care of the issue so quickly. I'm very much looking forward to the service. It's a great idea for advancing the IR field, thanks for making it happen!

**Comment by najtin** [comment]
the regex was fixed here https://github.com/ir-anthology/ir-anthology-acquisition/commit/2e1b3f654dd55d1b6cd81b08c2700dfb87629714
the change is live since https://github.com/ir-anthology/ir-anthology.github.io/commit/7e26829a4156750202af42841699759cc22d02c8
the index for the search will be rebuild soon

**Comment by najtin** [comment]
Index is now up-to-date.
