### ISSUE TITLE
Data: Multimedia IR (Ralph Ewerth via Mail)

### ISSUE THREAD

**Issue by matthias-hagen** [ir-anthology/ir-anthology#48]
Dabei ist mir etwas aufgefallen, die Multimedia-IR-Foren fehlen eigentlich noch, oder?

 

Das wären aus meiner Sicht: http://icmr2020.org/organisation.html#history

ICMR: ACM International Conference on Multimedia Retrieval (seit 2011) http://icmr2020.org/

CIVR: ACM International Conference on Image and Retrieval (2002 - 2010)

MIR: ACM Workshop on Multimedia Information Retrieval (2000 – 2010) @ ACM Multimedia

 

Und zB das Journal:

Int’l Journal on Multimedia Information Retrieval (IJMIR), Springer

**Comment by potthast** [comment]
See these issues: 
https://github.com/ir-anthology/ir-anthology/issues/31
https://github.com/ir-anthology/ir-anthology/issues/31

**Comment by sebgntr** [comment]
- [x] ICMR
- [ ] CIVR https://dblp.uni-trier.de/db/conf/civr/index.html
- [x] MIR
- [x] IJMIR
