### ISSUE TITLE
Data: Journal pages should separate entries by issue

### ISSUE THREAD

**Issue by potthast** [ir-anthology/ir-anthology#5]
Example: We have 148 papers for IP&M in 2019 (https://ir.webis.de/anthology/events/ipm_journals-2019/), and this seems to be only the first issue from 2019 -- there were six issues published that year (https://www.sciencedirect.com/journal/information-processing-and-management/issues).

**Comment by najtin** [comment]
why do you think that only the first is included?
i took "Characterizing and predicting downloads in academic search" from 2019 issue 3
https://www.sciencedirect.com/journal/information-processing-and-management/vol/56/issue/3
and it is in the ir-anthology https://ir.webis.de/anthology/2019.ipm_journals-56.7/

**Comment by potthast** [comment]
There's a misunderstanding here: While the individual Issues' papers are there, they are not properly separated, which is not how it should be.

![image](https://user-images.githubusercontent.com/1148967/111385991-de2db880-86ab-11eb-850e-cfda240f1e8f.png)

**Comment by najtin** [comment]
huh, we could either create multiple volumes - Volume 56 Issue 1 - Volume 56 Issue 2 -, or we adapt the anthology to have another optional layer (Issues). So that we then have conf/year/volume/issue

**Comment by potthast** [comment]
The volume number typically marks the number of years a periodical has been published.
The issue number the number of times the periodical has been published during a given year.
See: https://en.wikipedia.org/wiki/Periodical_literature#Volumes_and_issues

The fun part is this: volumes need not be aligned with years, apparently:
https://ir.webis.de/anthology/events/tois_journals-2015/
https://ir.webis.de/anthology/events/tois_journals-2016/
(Could you double-check if this is actually the case with TOIS?)

If volumes were aligned with years, this would be easy to solve: have one volume entry which is accessed from the landing page table by clicking on the two-digit year indicators, and within the volume entry, have one section for each issue.

In the case of TOIS (if it is correct), the situation is a bit more frustrating, if we do not wish to change too much... In that case, I guess, your solution is the best: Year-pages with sections by <volume>-<issuse>.

Hope that'll not be too complicated in the end... If it turns out to be complicated, let's discuss first.
