### ISSUE TITLE
Document how to manually add new Entries to the IR Anthology

### ISSUE THREAD

**Issue by mam10eks** [ir-anthology/ir-anthology#50]
Using DIR 2018 as example:

- Manually create bib entries
- Document the steps
- Changeover of IDs of PDFs for the search index (Bib-Key)
- Create new index in ir.chatnoir

Goal fo the next week
- Neue Version von IR-Anthology, mit ersten manuell eingetragenen Einträgen und aktualisierten IDs

**Comment by matthias-hagen** [comment]
I do not see a documentation of how to add new things in the README at https://github.com/ir-anthology/ir-anthology-data/tree/98a580fa84f75acd9c9fed10e194edaf1c871909#readme 

Please add it there!

**Comment by najtin** [comment]
huh, you are right. it should be linked

**Comment by najtin** [comment]
added it to the readme https://github.com/ir-anthology/ir-anthology-data/commit/4b40541f2171b162f10f2976f43bd9f398d798fd
