### ISSUE TITLE
Link to HTAi Information Retrieval Interest Group as society

### ISSUE THREAD

**Issue by sebgntr** [ir-anthology/ir-anthology#55]
https://htai.org/interest-groups/information-retrieval/

**Comment by najtin** [comment]
I am not sure what is to be added here. i could not find any information on the website regarding publishing papers. They have this resource segment, but these are only newsletters and alike. https://htai.org/interest-groups/information-retrieval/irg-resources/
@sebgntr

**Comment by sebgntr** [comment]
This should be part of the societies section IIRC.
