### ISSUE TITLE
Add SERI to societies

### ISSUE THREAD

**Issue by potthast** [ir-anthology/ir-anthology#61]
http://seri.org.es/ (not reachable)
Older versions exist in Web Archive: https://web.archive.org/web/20210118004256/http://seri.org.es/)
https://twitter.com/seri_org_es

**Comment by sebgntr** [comment]
The website is not reachable and Twitter is inactive.

**Comment by matthias-hagen** [comment]
I would suggest to first send a polite email to informacion@seri.org.es (mentioned on the Wayback link) and maybe approach the Twitter account to ask whether this national society is still active and what web page would be appropriate to link in the IR Antholgoy. When there is no reply in the next 14 days or so, I would suggest to add a gray link to the Wayback link in our IR Anthology ...

Second step could be to ask some Spanish IR people ... e.g., SIGIR 2022 local organizers in Madrid?!

**Comment by sebgntr** [comment]
(I collected all info on SERI into a new societies collection; requires frontend changes to display this data)
