### ISSUE TITLE
Data: Add CORIA to Conferences

### ISSUE THREAD

**Issue by potthast** [ir-anthology/ir-anthology#7]
http://www.asso-aria.org/coria/

**Comment by najtin** [comment]
I think this is it https://dblp.org/db/conf/coria/index.html but the last years are missing in the dblp

**Comment by potthast** [comment]
Josiane Moth offered help with this; I'll mail her with you on CC.

**Comment by najtin** [comment]
was already added https://github.com/ir-anthology/ir-anthology-data/commit/3a187bdbda58f02131377ff4edce8460a438b580
