### ISSUE TITLE
Data: WWW conference renaming

### ISSUE THREAD

**Issue by sebgntr** [ir-anthology/ir-anthology#73]
Keep an eye on the WWW conference, as its name is changing.

See: https://twitter.com/gdm3000/status/1421899037456879624?s=19

**Comment by najtin** [comment]
The name change should take effect next year - so i suggest leaving this issue open until it is dealt with sometime next year

**Comment by sebgntr** [comment]
DBLP kept the name, so no changes required: https://ir.webis.de/anthology/events/wwwconf_conference-2022/
