### ISSUE TITLE
Unique format for bib/citation keys

### ISSUE THREAD

**Issue by sebgntr** [ir-anthology/ir-anthology#74]
Have one unique format for publications. For simplicity, follow the ACL Anthology format: `<up-to-2-names>-<year>-<first-word>`
E.g.: `alice-bob-2021-identifying` or `carol-etal-2021-analyzing` or `dave-2021-summarizing`

(code/rules for generating: https://github.com/acl-org/acl-anthology/blob/9c9d9ddceb190992decd52b742bc040b37634b81/bin/anthology/index.py#L209)

Benefits:
- Word from title should avoid collisions
- Word from title helps with identifying the correct citation key (when using autocompletion)
- Author and year are usually known (when using autocompletion)

Related to: https://github.com/ir-anthology/ir-anthology/issues/72

**Comment by potthast** [comment]
Please also add a copy button for just the key: https://twitter.com/damiano10/status/1421469676949762051
This would of course also presume that the entire Bibtex file can be downloaded.

**Comment by sebgntr** [comment]
We've updated the naming scheme to `<last-name-of-first-author>-<year>-<first-non-stopword>[-<number-to-resolve-collisions>]`.
