### ISSUE TITLE
Reduce the font size of the linked breadcrumbs on a paper's page to 8pt or 10pt (i.e., very small)

### ISSUE THREAD

**Issue by potthast** [ir-anthology/ir-anthology#97]
In this view of a paper, its title should stick out most:

![image](https://user-images.githubusercontent.com/1148967/152766723-c70db3b0-43b7-4e8c-850d-f6c6abca9708.png)

But this is not the case: The breadcrumbs above the paper's title are completely distracting from the title itself.
Breadcrumb are important and should stay where they are, but their font size should be reduced to the size that breadcrumbs usually have: 8pt, or 10pt, that is, as small as possible while still being readable and usable on all desktop and touch devices.

**Comment by najtin** [comment]
is this fine? 
![image](https://user-images.githubusercontent.com/42641080/155720665-afc1dffc-16d9-4af2-90b4-37ccf634a891.png)
