### ISSUE TITLE
Paper view: Move the BibTex entry into the above table.

### ISSUE THREAD

**Issue by potthast** [ir-anthology/ir-anthology#99]
This view does not look very nice:

![image](https://user-images.githubusercontent.com/1148967/153048969-51fc8a12-febd-4f73-9927-0be82697c74b.png)

Problems include:
- Too many borders
- Tabbing with just one tab
- More than one heading
- Redundancy of "BibTex" in the table and "BibTex as tab header
- Redundant download and copy to clipboard buttons

Suggestion:
- Put the gray pre-environment that shows the entry into the table, right next to "BibTex:"
- Put the buttons either above or below (probably above is better, since that may be more important to see and use quickly to many)
- Reduce the font size

Small thing to fix on the side:
- The `crossref` key's equals sign within the Bibentry is not aligned with the remaining equals signs.

**Comment by najtin** [comment]
Is this what you had in mind? Would this be small enough? 
![image](https://user-images.githubusercontent.com/42641080/155722701-5584685e-f387-4827-b93d-9481ef09a465.png)

**Comment by najtin** [comment]
The alignment of the "=" should be tracked in another issue.
